MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.01

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,42 +4,62 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=34
-    - CONDA_PY=35
-    - CONDA_PY=36
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "FoIZZzrPzI6GllrMbWepJF5MnnEn2ItLz53Kh29v99FAVshq4Ayly5CNLfy3/PiY+0yjQjaoWFQwXyYvTtMjyNEdj+zGBtwbWMqXyuV6Ae+8CuGQAG7BTDTRXH3BC/i3DXT7RVDf+/Xp8pYXcok1egbGyWKPiH4b4XLGTC4Dnot7Uvf0z+NgUGn9/d36Dt6X0We7R1PMyDpQHsmk80Tz0JoJSQLX69q5QQP51AzO2M/B+mhhnS/jPQd8QOmI49rVR/y5GPwd02twihL8CDdMQcowTLyt+kdL0lpAOU13e/0EWqoYp5RUGcohZA0Vvvbw4qqRMtXWDMzJ8M8VsTLdCrB/x32fdLnQ49xXMCPCPwy/iTD9zuZ5GDICq02TrcbGi85HRRJ8rWlqnRKtAVbMS+9gMr+jkbhkJfZWV2valIwB3PLv1W6Btc/qev8cJldFBICOBI2gvVEPtaZGMHP3Jhje3dnJFnr8c7zsQKL0zIYJb4o/k/PlzBoWuwYFj/nrVxI73qcbjWAqGgfzrLA9FOEWcsspPvbrm/W1ULNetQISmAG/+zapPFyW4LqGg/k7QLM9ezwCB715jySRERkTp+ufb4rDcrAidqHET8JeHgA8SfhU9HgrxxKuoP9pgDHSerYzwsTkYcfPkNY17q/lNQjpplooIw6dWiQ4y8kbKlk="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --remove channels defaults
-      conda config --add channels defaults
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
